[SxSExport-Configuration]

;如无特殊说明，1--执行操作 0--不做处理

;脚本版本
Scr_Ver=v_2026.3.28

;1--dism 重新输出【映像】文件，体积大一点，时间短一点
;2--wimlib-imagex.exe 优化映像文件，体积稍小一点，时间长一点
Flag_optimize=1

;组件移除：1--dism命令  2--install_wim_tweak.exe
Flag_REMode=1

;APPX
Flag_RemoveA=1

;组件
Flag_RemoveC=1

;可选功能
Flag_RemoveF=1

;生成保留列表
Flag_Retain=1

;生成移除列表
Flag_Import=1

;极限精简模式
Flag_SuperLite=1

;删除新版Edge
Flag_Edge=1

;挂载映像 删除空目录
Flag_Empty=1

;dism 方式 组件清理
Flag_ComCleanup=1

;以下暂时无用
;增强模式
Flag_Plus=1
;组件导出日志
Flag_Log=0
;生成CAB文件
Flag_CAB=0
;手动模式循导出标志 当 Flag_Plus=0 时，以下配置才生效
Loop=1
;0--手动模式自动搜索语言包 1--手动搜索语言包
Flag_NoAutoMUI=0
